algo = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(algo))
print('Só tem espaços ?', algo.isspace())
print('É um número ?', algo.isnumeric())
print('É alfabetico ?', algo.isalpha())
print('É alfanuúmerico ?', algo.isalnum())
print('Esta em maiúsculas', algo.isupper())
print('Esta em minusculas ?', algo.islower())
print('Está capitalizada ?', algo.istitle())
